import { ErrandPost } from "@/types/post";

export const mockPosts: ErrandPost[] = [
  {
    id: "1",
    title: "Weekly Grocery Run @ H-E-B",
    type: "Grocery Shopping",
    description: "Need someone to pick up my weekly groceries from H-E-B on Lamar. List includes produce, dairy, and household items. Bags provided.",
    reward: 18,
    status: "Pending Pickup",
    date: "2026-05-14",
    time: "10:00 AM",
    location: "Austin, TX",
    serviceType: "Delivery",
    assignedTo: null,
    icon: "shopping-cart",
  },
  {
    id: "2",
    title: "Deliver Birthday Gift Box",
    type: "Package Delivery",
    description: "Drop off a pre-packed gift box to a friend's address in South Austin. Fragile - please handle with care. Signature required.",
    reward: 12,
    status: "ASAP",
    date: "2026-05-11",
    time: "2:00 PM",
    location: "South Austin, TX",
    serviceType: "Delivery",
    assignedTo: null,
    icon: "package",
  },
  {
    id: "3",
    title: "2BR Apartment Deep Clean",
    type: "Home Cleaning",
    description: "Full deep clean of my 2-bedroom apartment before guests arrive this weekend. Kitchen, bathrooms, floors, and dusting required.",
    reward: 75,
    status: "Scheduled",
    date: "2026-05-16",
    time: "09:00 AM",
    location: "Austin, TX",
    serviceType: "Pickup",
    assignedTo: "Destiny W.",
    icon: "cleaning",
  },
  {
    id: "4",
    title: "Dog Walking - 2 Golden Retrievers",
    type: "Pet Care",
    description: "30-minute walk for my two golden retrievers (Biscuit & Maple) in the Barton Hills neighborhood. Dogs are friendly and leash-trained.",
    reward: 16,
    status: "In Progress",
    date: "2026-05-11",
    time: "04:30 PM",
    location: "Barton Hills, TX",
    serviceType: "Pickup",
    assignedTo: "Sofia R.",
    icon: "pet",
  },
  {
    id: "5",
    title: "Dry Cleaning Pickup & Drop-off",
    type: "Dry Cleaning",
    description: "Pick up 3 suits and 2 dresses from my place and drop them off at the dry cleaner on Congress Ave. Return same day if possible.",
    reward: 20,
    status: "Completed",
    date: "2026-05-08",
    time: "11:00 AM",
    location: "Congress Ave, TX",
    serviceType: "Both",
    assignedTo: "Mei-Lin P.",
    icon: "dry-cleaning",
  },
  {
    id: "6",
    title: "Lunch Pickup - Torchy's Tacos",
    type: "Food Pickup",
    description: "Grab a lunch order for 3 people from Torchy's Tacos on S. 1st. Order will be pre-placed. Just pay & bring; reimbursement included.",
    reward: 10,
    status: "Completed",
    date: "2026-05-08",
    time: "12:30 PM",
    location: "S. 1st St, Austin, TX",
    serviceType: "Delivery",
    assignedTo: "Marcus T.",
    icon: "food",
  },
  {
    id: "7",
    title: "Dog Walking - 2 Golden Retrievers",
    type: "Pet Care",
    description: "30-minute walk for my two golden retrievers (Biscuit & Maple) in the Barton Hills neighborhood. Dogs are friendly and leash-trained.",
    reward: 16,
    status: "In Progress",
    date: "2026-05-11",
    time: "04:30 PM",
    location: "Barton Hills, TX",
    serviceType: "Pickup",
    assignedTo: "Sofia R.",
    icon: "pet",
  },
  {
    id: "8",
    title: "Dry Cleaning Pickup & Drop-off",
    type: "Dry Cleaning",
    description: "Pick up 3 suits and 2 dresses from my place and drop them off at the dry cleaner on Congress Ave. Return same day if possible.",
    reward: 20,
    status: "Completed",
    date: "2026-05-08",
    time: "11:00 AM",
    location: "Congress Ave, TX",
    serviceType: "Both",
    assignedTo: "Mei-Lin P.",
    icon: "dry-cleaning",
  },
  {
    id: "9",
    title: "Lunch Pickup - Torchy's Tacos",
    type: "Food Pickup",
    description: "Grab a lunch order for 3 people from Torchy's Tacos on S. 1st. Order will be pre-placed. Just pay & bring; reimbursement included.",
    reward: 10,
    status: "Completed",
    date: "2026-05-08",
    time: "12:30 PM",
    location: "S. 1st St, Austin, TX",
    serviceType: "Delivery",
    assignedTo: "Marcus T.",
    icon: "food",
  },
];

export const statusCounts = {
  All: 12,
  "Pending Pickup": 2,
  ASAP: 2,
  "Scheduled": 2,
  "In Progress": 2,
  Completed: 3,
  "Cancelled": 2,
};

export const statuses = [
  "All",
  "Pending Pickup",
  "ASAP",
  "Scheduled",
  "In Progress",
  "Completed",
  "Cancelled",
] as const;
