import { Montserrat } from "next/font/google";
import Footer from "../components/website/Footer";
import Header from "../components/website/Header";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={`${montserrat.variable} h-full antialiased`}>
      <body className='min-h-screen flex flex-col font-sans'>
        <Header />
        <main className='flex flex-1'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
